### ISSUE TITLE
feat: setting prometheus for monitoring

### ISSUE THREAD

**Issue by JuseungL** [DrinkHere/backend#5]
# Title

- setting prometheus for monitoring

# TODO

- [x] Add actuator and prometheus dependencies
- [x] Set actuator related yaml file
- [x] Set up prometheus.yml and docker-compose.yml on the monitoring instance.

# etc

- nothing
